### ISSUE TITLE
Release new docker images

### ISSUE THREAD

**Issue by pabloromanelli** [zeebe-io/zeebe-http-worker#76]
Hi, I can't see in docker hub the latest versions deployed: 
https://hub.docker.com/r/camunda/zeebe-http-worker/tags

Only the `SNAPSHOT` image was updated.

Would it be possible to have all the other versions deployed individually?

**Comment by saig0** [comment]
Hi @pabloromanelli,

thank you for raising this up. Too much time has passed since the last release :see_no_evil: 

Unfortunately, I lost track after the project was used in the Camunda cloud. Since it is not used anymore in the cloud, I'll take it over again. 

I'll update a few things and then build a new release and publish the docker image. Stay tuned :balloon:

**Comment by saig0** [comment]
The new release is out: https://github.com/zeebe-io/zeebe-http-worker/releases/tag/0.23.0

Also, available on DockerHub: `docker pull camunda/zeebe-http-worker:0.23.0`
